#!/bin/bash
echo -e "\074settings>\n \074localRepository>$OPENSHIFT_DATA_DIR\074/localRepository>\n\074/settings>\n" > "$OPENSHIFT_REPO_DIR".openshift/settings.xml

cd $OPENSHIFT_REPO_DIR
mvn package -s .openshift/settings.xml -DskipTests=true
