language: java
jdk:
- oraclejdk7
- openjdk7
deploy:
  provider: openshift
  user: scatu637@yahoo.com.ar
  password:
    secure: ZjMi7qYQD23wuzjRPnsSnujQ5B+RWCroXrdY9d7ky/kQyJb5yduZtn7Ll25ClhSCoduWK/uo4ah4jHQ0hE61DHbYD8tnwq+ZUNfq29nJUNjSnSawm9dxfqwq40zfDmyAtBU03wUMkxNVldpyrTbJXK5Xf2BUM6Smm0ykWSmSEIg=
  app: todo-oauth-provider
  domain: oauth
  on:
    repo: sebastianscatularo/todo-oauth-provider
